#!/usr/bin/env bash
set -euo pipefail

LUOPO_LDNMP_ITEMS=(
  "1|安装LDNMP环境 ★|luopo_ldnmp_install_all"
  "2|安装WordPress ★|luopo_ldnmp_install_wordpress"
  "3|安装Discuz论坛|luopo_ldnmp_install_discuz"
  "4|安装可道云桌面|luopo_ldnmp_install_kodbox"
  "5|安装苹果CMS影视站|luopo_ldnmp_launch_compat"
  "6|安装独角数发卡网|luopo_ldnmp_launch_compat"
  "7|安装flarum论坛网站|luopo_ldnmp_launch_compat"
  "8|安装typecho轻量博客网站|luopo_ldnmp_install_typecho"
  "9|安装LinkStack共享链接平台|luopo_ldnmp_install_linkstack"
  "20|自定义动态站点|luopo_ldnmp_launch_compat"
  "21|仅安装nginx ★|luopo_ldnmp_install_nginx_only"
  "22|站点重定向|luopo_ldnmp_redirect_site"
  "23|站点反向代理-IP+端口 ★|luopo_ldnmp_reverse_proxy_ip_port"
  "24|站点反向代理-域名|luopo_ldnmp_reverse_proxy_domain"
  "25|安装Bitwarden密码管理平台|luopo_ldnmp_install_bitwarden"
  "26|安装Halo博客网站|luopo_ldnmp_install_halo"
  "27|安装AI绘画提示词生成器|luopo_ldnmp_install_ai_prompt_generator"
  "28|站点反向代理-负载均衡|luopo_ldnmp_reverse_proxy_load_balance"
  "29|Stream四层代理转发|luopo_ldnmp_stream_proxy"
  "30|自定义静态站点|luopo_ldnmp_custom_static_site"
  "31|站点数据管理 ★|luopo_ldnmp_site_status"
  "32|备份全站数据|luopo_ldnmp_backup_all"
  "33|定时远程备份|luopo_ldnmp_scheduled_remote_backup"
  "34|还原全站数据|luopo_ldnmp_restore_all"
  "35|防护LDNMP环境|luopo_ldnmp_security"
  "36|优化LDNMP环境|luopo_ldnmp_optimization"
  "37|更新LDNMP环境|luopo_ldnmp_update_menu"
  "38|卸载LDNMP环境|luopo_ldnmp_uninstall"
)

LUOPO_LDNMP_LAYOUT=(
  "1|2"
  "3|4"
  "5|6"
  "7|8"
  "9|20"
  "---"
  "21|22"
  "23|24"
  "25|26"
  "27|28"
  "29|30"
  "---"
  "31|32"
  "33|34"
  "---"
  "35|36"
  "37|38"
)

