#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MENU_FILE="$ROOT_DIR/core/menu.sh"
LUOPO_NETWORK_TEST_MENU_FILE="$ROOT_DIR/modules/luopo/network_test/menu.sh"
LUOPO_NETWORK_TEST_REGISTRY_FILE="$ROOT_DIR/modules/luopo/network_test/registry.sh"
LUOPO_NETWORK_TEST_ACTIONS_FILE="$ROOT_DIR/modules/luopo/network_test/actions.sh"
LUOPO_NETWORK_TEST_HELPERS_FILE="$ROOT_DIR/modules/luopo/network_test/helpers.sh"
LUOPO_BASIC_TOOLS_MENU_FILE="$ROOT_DIR/modules/luopo/basic_tools/menu.sh"
LUOPO_BASIC_TOOLS_REGISTRY_FILE="$ROOT_DIR/modules/luopo/basic_tools/registry.sh"
LUOPO_BASIC_TOOLS_ACTIONS_FILE="$ROOT_DIR/modules/luopo/basic_tools/actions.sh"
LUOPO_BASIC_TOOLS_HELPERS_FILE="$ROOT_DIR/modules/luopo/basic_tools/helpers.sh"
LUOPO_BBR_MENU_FILE="$ROOT_DIR/modules/luopo/bbr_management/menu.sh"
LUOPO_BBR_ACTIONS_FILE="$ROOT_DIR/modules/luopo/bbr_management/actions.sh"
LUOPO_BBR_HELPERS_FILE="$ROOT_DIR/modules/luopo/bbr_management/helpers.sh"
LUOPO_ORACLE_CLOUD_MENU_FILE="$ROOT_DIR/modules/luopo/oracle_cloud/menu.sh"
LUOPO_ORACLE_CLOUD_REGISTRY_FILE="$ROOT_DIR/modules/luopo/oracle_cloud/registry.sh"
LUOPO_ORACLE_CLOUD_ACTIONS_FILE="$ROOT_DIR/modules/luopo/oracle_cloud/actions.sh"
LUOPO_ORACLE_CLOUD_HELPERS_FILE="$ROOT_DIR/modules/luopo/oracle_cloud/helpers.sh"
LUOPO_WORKSPACE_MENU_FILE="$ROOT_DIR/modules/luopo/workspace/menu.sh"
LUOPO_WORKSPACE_REGISTRY_FILE="$ROOT_DIR/modules/luopo/workspace/registry.sh"
LUOPO_WORKSPACE_ACTIONS_FILE="$ROOT_DIR/modules/luopo/workspace/actions.sh"
LUOPO_WORKSPACE_HELPERS_FILE="$ROOT_DIR/modules/luopo/workspace/helpers.sh"
LUOPO_CLUSTER_MENU_FILE="$ROOT_DIR/modules/luopo/cluster_control/menu.sh"
LUOPO_CLUSTER_REGISTRY_FILE="$ROOT_DIR/modules/luopo/cluster_control/registry.sh"
LUOPO_CLUSTER_ACTIONS_FILE="$ROOT_DIR/modules/luopo/cluster_control/actions.sh"
LUOPO_CLUSTER_HELPERS_FILE="$ROOT_DIR/modules/luopo/cluster_control/helpers.sh"
LUOPO_DOCKER_MANAGER_FILE="$ROOT_DIR/modules/luopo/docker/manager.sh"
LUOPO_DOCKER_COMMON_FILE="$ROOT_DIR/modules/luopo/docker/parts/common.sh"
LUOPO_DOCKER_INSTALL_STATUS_FILE="$ROOT_DIR/modules/luopo/docker/parts/install_status.sh"
LUOPO_DOCKER_RESOURCES_FILE="$ROOT_DIR/modules/luopo/docker/parts/resources.sh"
LUOPO_DOCKER_DAEMON_BACKUP_FILE="$ROOT_DIR/modules/luopo/docker/parts/daemon_backup.sh"
LUOPO_APP_MARKET_MENU_FILE="$ROOT_DIR/modules/luopo/app_marketplace/menu.sh"
LUOPO_APP_MARKET_REGISTRY_FILE="$ROOT_DIR/modules/luopo/app_marketplace/registry.sh"
LUOPO_APP_MARKET_ACTIONS_FILE="$ROOT_DIR/modules/luopo/app_marketplace/actions.sh"
LUOPO_APP_MARKET_HELPERS_FILE="$ROOT_DIR/modules/luopo/app_marketplace/helpers.sh"
LUOPO_APP_MARKET_NATIVE_APPS_FILE="$ROOT_DIR/modules/luopo/app_marketplace/native_apps.sh"
LUOPO_APP_MARKET_NATIVE_COMMON_FILE="$ROOT_DIR/modules/luopo/app_marketplace/native/common.sh"
LUOPO_APP_MARKET_NATIVE_PANELS_FILE="$ROOT_DIR/modules/luopo/app_marketplace/native/panels.sh"
LUOPO_APP_MARKET_NATIVE_FILES_MEDIA_FILE="$ROOT_DIR/modules/luopo/app_marketplace/native/files_media.sh"
LUOPO_APP_MARKET_NATIVE_NETWORK_SECURITY_FILE="$ROOT_DIR/modules/luopo/app_marketplace/native/network_security.sh"
LUOPO_APP_MARKET_NATIVE_AI_PRODUCTIVITY_FILE="$ROOT_DIR/modules/luopo/app_marketplace/native/ai_productivity.sh"
LUOPO_APP_MARKET_NATIVE_FILES=(
  "$LUOPO_APP_MARKET_NATIVE_APPS_FILE"
  "$LUOPO_APP_MARKET_NATIVE_COMMON_FILE"
  "$LUOPO_APP_MARKET_NATIVE_PANELS_FILE"
  "$LUOPO_APP_MARKET_NATIVE_FILES_MEDIA_FILE"
  "$LUOPO_APP_MARKET_NATIVE_NETWORK_SECURITY_FILE"
  "$LUOPO_APP_MARKET_NATIVE_AI_PRODUCTIVITY_FILE"
)
LUOPO_WARP_MENU_FILE="$ROOT_DIR/modules/luopo/warp_management/menu.sh"
LUOPO_WARP_REGISTRY_FILE="$ROOT_DIR/modules/luopo/warp_management/registry.sh"
LUOPO_WARP_ACTIONS_FILE="$ROOT_DIR/modules/luopo/warp_management/actions.sh"
LUOPO_WARP_HELPERS_FILE="$ROOT_DIR/modules/luopo/warp_management/helpers.sh"
LUOPO_SYSTEM_TOOLS_MENU_FILE="$ROOT_DIR/modules/luopo/system_tools/menu.sh"
LUOPO_SYSTEM_TOOLS_REGISTRY_FILE="$ROOT_DIR/modules/luopo/system_tools/registry.sh"
LUOPO_SYSTEM_TOOLS_ACTIONS_FILE="$ROOT_DIR/modules/luopo/system_tools/actions.sh"
LUOPO_SYSTEM_TOOLS_ACTIONS_ACCESS_FILE="$ROOT_DIR/modules/luopo/system_tools/actions_access.sh"
LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE="$ROOT_DIR/modules/luopo/system_tools/actions_operations.sh"
LUOPO_SYSTEM_TOOLS_ACTIONS_MISC_FILE="$ROOT_DIR/modules/luopo/system_tools/actions_misc.sh"
LUOPO_SYSTEM_TOOLS_MISC_MAINTENANCE_FILE="$ROOT_DIR/modules/luopo/system_tools/misc/maintenance.sh"
LUOPO_SYSTEM_TOOLS_MISC_BACKUP_FILE="$ROOT_DIR/modules/luopo/system_tools/misc/backup_file.sh"
LUOPO_SYSTEM_TOOLS_MISC_SYNC_REMOTE_FILE="$ROOT_DIR/modules/luopo/system_tools/misc/sync_remote.sh"
LUOPO_SYSTEM_TOOLS_MISC_SECURITY_DISK_KERNEL_FILE="$ROOT_DIR/modules/luopo/system_tools/misc/security_disk_kernel.sh"
LUOPO_SYSTEM_TOOLS_MISC_FILES=(
  "$LUOPO_SYSTEM_TOOLS_ACTIONS_MISC_FILE"
  "$LUOPO_SYSTEM_TOOLS_MISC_MAINTENANCE_FILE"
  "$LUOPO_SYSTEM_TOOLS_MISC_BACKUP_FILE"
  "$LUOPO_SYSTEM_TOOLS_MISC_SYNC_REMOTE_FILE"
  "$LUOPO_SYSTEM_TOOLS_MISC_SECURITY_DISK_KERNEL_FILE"
)
LUOPO_SYSTEM_TOOLS_HELPERS_FILE="$ROOT_DIR/modules/luopo/system_tools/helpers.sh"
LUOPO_LDNMP_MENU_FILE="$ROOT_DIR/modules/luopo/ldnmp/menu.sh"
LUOPO_LDNMP_REGISTRY_FILE="$ROOT_DIR/modules/luopo/ldnmp/registry.sh"
LUOPO_LDNMP_ACTIONS_FILE="$ROOT_DIR/modules/luopo/ldnmp/actions.sh"
LUOPO_LDNMP_ACTIONS_SITES_FILE="$ROOT_DIR/modules/luopo/ldnmp/actions_sites.sh"
LUOPO_LDNMP_ACTIONS_PROXY_FILE="$ROOT_DIR/modules/luopo/ldnmp/actions_proxy.sh"
LUOPO_LDNMP_ACTIONS_PROXY_CORE_FILE="$ROOT_DIR/modules/luopo/ldnmp/actions_proxy_core.sh"
LUOPO_LDNMP_ACTIONS_STREAM_FILE="$ROOT_DIR/modules/luopo/ldnmp/actions_stream.sh"
LUOPO_LDNMP_ACTIONS_SITE_STATUS_FILE="$ROOT_DIR/modules/luopo/ldnmp/actions_site_status.sh"
LUOPO_LDNMP_ACTIONS_SECURITY_FILE="$ROOT_DIR/modules/luopo/ldnmp/actions_security.sh"
LUOPO_LDNMP_ACTIONS_OPTIMIZATION_FILE="$ROOT_DIR/modules/luopo/ldnmp/actions_optimization.sh"
LUOPO_LDNMP_ACTIONS_MAINTENANCE_FILE="$ROOT_DIR/modules/luopo/ldnmp/actions_maintenance.sh"
LUOPO_LDNMP_HELPERS_FILE="$ROOT_DIR/modules/luopo/ldnmp/helpers.sh"
LUOPO_LDNMP_HELPERS_INSTALL_FILE="$ROOT_DIR/modules/luopo/ldnmp/helpers_install.sh"
LUOPO_LDNMP_HELPERS_RUNTIME_FILE="$ROOT_DIR/modules/luopo/ldnmp/helpers_runtime.sh"
LUOPO_LDNMP_HELPERS_SITE_FILE="$ROOT_DIR/modules/luopo/ldnmp/helpers_site.sh"
TOOLKIT_FILE="$ROOT_DIR/toolkit.sh"
INSTALL_FILE="$ROOT_DIR/install.sh"
UNINSTALL_FILE="$ROOT_DIR/core/uninstall.sh"
REGISTRY_FILE="$ROOT_DIR/core/menu_registry.sh"
DISPATCHER_FILE="$ROOT_DIR/core/menu_dispatcher.sh"
ENTRIES_LOAD_FILE="$ROOT_DIR/modules/entries.sh"

fail() {
  echo "::error title=smoke_menu::$*"
  echo "[FAIL] $*"
  exit 1
}

assert_file() {
  file="$1"
  [[ -f "$file" ]] || fail "missing file: $file"
}

assert_contains_fixed() {
  file="$1"
  text="$2"
  desc="$3"
  grep -Fq -- "$text" "$file" || fail "$desc (missing: $text)"
}

assert_contains_regex() {
  file="$1"
  pattern="$2"
  desc="$3"
  grep -Eq "$pattern" "$file" || fail "$desc (pattern: $pattern)"
}

assert_native_contains_fixed() {
  text="$1"
  desc="$2"
  grep -Fq -- "$text" "${LUOPO_APP_MARKET_NATIVE_FILES[@]}" || fail "$desc (missing: $text)"
}

assert_native_contains_regex() {
  pattern="$1"
  desc="$2"
  grep -Eq "$pattern" "${LUOPO_APP_MARKET_NATIVE_FILES[@]}" || fail "$desc (pattern: $pattern)"
}

assert_system_misc_contains_regex() {
  pattern="$1"
  desc="$2"
  grep -Eq "$pattern" "${LUOPO_SYSTEM_TOOLS_MISC_FILES[@]}" || fail "$desc (pattern: $pattern)"
}

assert_not_contains_fixed() {
  file="$1"
  text="$2"
  desc="$3"
  if grep -Fq -- "$text" "$file"; then
    fail "$desc (unexpected: $text)"
  fi
}

main() {
  assert_file "$MENU_FILE"
  assert_file "$LUOPO_NETWORK_TEST_MENU_FILE"
  assert_file "$LUOPO_NETWORK_TEST_REGISTRY_FILE"
  assert_file "$LUOPO_NETWORK_TEST_ACTIONS_FILE"
  assert_file "$LUOPO_NETWORK_TEST_HELPERS_FILE"
  assert_file "$LUOPO_BASIC_TOOLS_MENU_FILE"
  assert_file "$LUOPO_BASIC_TOOLS_REGISTRY_FILE"
  assert_file "$LUOPO_BASIC_TOOLS_ACTIONS_FILE"
  assert_file "$LUOPO_BASIC_TOOLS_HELPERS_FILE"
  assert_file "$LUOPO_BBR_MENU_FILE"
  assert_file "$LUOPO_BBR_ACTIONS_FILE"
  assert_file "$LUOPO_BBR_HELPERS_FILE"
  assert_file "$LUOPO_ORACLE_CLOUD_MENU_FILE"
  assert_file "$LUOPO_ORACLE_CLOUD_REGISTRY_FILE"
  assert_file "$LUOPO_ORACLE_CLOUD_ACTIONS_FILE"
  assert_file "$LUOPO_ORACLE_CLOUD_HELPERS_FILE"
  assert_file "$LUOPO_WORKSPACE_MENU_FILE"
  assert_file "$LUOPO_WORKSPACE_REGISTRY_FILE"
  assert_file "$LUOPO_WORKSPACE_ACTIONS_FILE"
  assert_file "$LUOPO_WORKSPACE_HELPERS_FILE"
  assert_file "$LUOPO_CLUSTER_MENU_FILE"
  assert_file "$LUOPO_CLUSTER_REGISTRY_FILE"
  assert_file "$LUOPO_CLUSTER_ACTIONS_FILE"
  assert_file "$LUOPO_CLUSTER_HELPERS_FILE"
  assert_file "$LUOPO_DOCKER_MANAGER_FILE"
  assert_file "$LUOPO_DOCKER_COMMON_FILE"
  assert_file "$LUOPO_DOCKER_INSTALL_STATUS_FILE"
  assert_file "$LUOPO_DOCKER_RESOURCES_FILE"
  assert_file "$LUOPO_DOCKER_DAEMON_BACKUP_FILE"
  assert_file "$LUOPO_APP_MARKET_MENU_FILE"
  assert_file "$LUOPO_APP_MARKET_REGISTRY_FILE"
  assert_file "$LUOPO_APP_MARKET_ACTIONS_FILE"
  assert_file "$LUOPO_APP_MARKET_HELPERS_FILE"
  assert_file "$LUOPO_APP_MARKET_NATIVE_APPS_FILE"
  assert_file "$LUOPO_APP_MARKET_NATIVE_COMMON_FILE"
  assert_file "$LUOPO_APP_MARKET_NATIVE_PANELS_FILE"
  assert_file "$LUOPO_APP_MARKET_NATIVE_FILES_MEDIA_FILE"
  assert_file "$LUOPO_APP_MARKET_NATIVE_NETWORK_SECURITY_FILE"
  assert_file "$LUOPO_APP_MARKET_NATIVE_AI_PRODUCTIVITY_FILE"
  assert_file "$LUOPO_WARP_MENU_FILE"
  assert_file "$LUOPO_WARP_REGISTRY_FILE"
  assert_file "$LUOPO_WARP_ACTIONS_FILE"
  assert_file "$LUOPO_WARP_HELPERS_FILE"
  assert_file "$LUOPO_SYSTEM_TOOLS_MENU_FILE"
  assert_file "$LUOPO_SYSTEM_TOOLS_REGISTRY_FILE"
  assert_file "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE"
  assert_file "$LUOPO_SYSTEM_TOOLS_ACTIONS_ACCESS_FILE"
  assert_file "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE"
  assert_file "$LUOPO_SYSTEM_TOOLS_ACTIONS_MISC_FILE"
  assert_file "$LUOPO_SYSTEM_TOOLS_MISC_MAINTENANCE_FILE"
  assert_file "$LUOPO_SYSTEM_TOOLS_MISC_BACKUP_FILE"
  assert_file "$LUOPO_SYSTEM_TOOLS_MISC_SYNC_REMOTE_FILE"
  assert_file "$LUOPO_SYSTEM_TOOLS_MISC_SECURITY_DISK_KERNEL_FILE"
  assert_file "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE"
  assert_file "$LUOPO_LDNMP_MENU_FILE"
  assert_file "$LUOPO_LDNMP_REGISTRY_FILE"
  assert_file "$LUOPO_LDNMP_ACTIONS_FILE"
  assert_file "$LUOPO_LDNMP_ACTIONS_SITES_FILE"
  assert_file "$LUOPO_LDNMP_ACTIONS_PROXY_FILE"
  assert_file "$LUOPO_LDNMP_ACTIONS_PROXY_CORE_FILE"
  assert_file "$LUOPO_LDNMP_ACTIONS_STREAM_FILE"
  assert_file "$LUOPO_LDNMP_ACTIONS_SITE_STATUS_FILE"
  assert_file "$LUOPO_LDNMP_ACTIONS_SECURITY_FILE"
  assert_file "$LUOPO_LDNMP_ACTIONS_OPTIMIZATION_FILE"
  assert_file "$LUOPO_LDNMP_ACTIONS_MAINTENANCE_FILE"
  assert_file "$LUOPO_LDNMP_HELPERS_FILE"
  assert_file "$LUOPO_LDNMP_HELPERS_INSTALL_FILE"
  assert_file "$LUOPO_LDNMP_HELPERS_RUNTIME_FILE"
  assert_file "$LUOPO_LDNMP_HELPERS_SITE_FILE"
  assert_file "$TOOLKIT_FILE"
  assert_file "$INSTALL_FILE"
  assert_file "$UNINSTALL_FILE"
  assert_file "$REGISTRY_FILE"
  assert_file "$DISPATCHER_FILE"
  assert_file "$ENTRIES_LOAD_FILE"

  for label in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 99 88 0; do
    assert_contains_fixed "$REGISTRY_FILE" "\"${label}|menu_label_${label}" "missing menu registry item ${label}"
  done

  assert_contains_fixed "$MENU_FILE" 'source "$ROOT_DIR/core/menu_registry.sh"' "menu should load registry"
  assert_contains_fixed "$MENU_FILE" 'source "$ROOT_DIR/core/menu_dispatcher.sh"' "menu should load dispatcher"
  assert_contains_fixed "$MENU_FILE" 'source "$ROOT_DIR/modules/entries.sh"' "menu should load entry handlers"
  assert_not_contains_fixed "$MENU_FILE" 'modules/compat/load.sh' "menu should not load compat handlers"
  assert_not_contains_fixed "$MENU_FILE" 'source "$ROOT_DIR/modules/luopo_bridge.sh"' "menu should not source legacy bridge"
  assert_not_contains_fixed "$MENU_FILE" 'source "$ROOT_DIR/modules/features/load.sh"' "menu should not source legacy features loader"
  assert_contains_fixed "$MENU_FILE" 'for item in "${MENU_ITEMS[@]}"; do' "menu should render items from registry"
  assert_contains_fixed "$MENU_FILE" 'dispatch_menu_action "$choice"' "menu should dispatch choices via dispatcher"
  assert_contains_fixed "$MENU_FILE" 'if [[ "$choice" == "00" ]]; then' "menu should remap 00 to 99"

  assert_contains_fixed "$DISPATCHER_FILE" 'entry_exit' "dispatcher should support exit handler"
  assert_contains_fixed "$DISPATCHER_FILE" 'run_action "$action_name" "$handler"' "dispatcher should execute handler via run_action"
  assert_contains_fixed "$DISPATCHER_FILE" 'if [[ "$pause_mode" == "press_enter" ]]; then' "dispatcher should honor pause mode"
  assert_contains_fixed "$TOOLKIT_FILE" 'COMMAND="${1:-}"' "toolkit should capture command argument"
  assert_contains_fixed "$TOOLKIT_FILE" 'if [[ "$COMMAND" == "rsync_run" ]]; then' "toolkit should expose rsync cron runner"
  assert_contains_fixed "$TOOLKIT_FILE" 'luopo_system_tools_rsync_run_task push "${1:-}"' "toolkit rsync runner should call native rsync task"

  for feature_file in \
    entry_system_info.sh \
    entry_system_update.sh \
    entry_system_cleanup.sh \
    entry_scripts_hub.sh \
    entry_basic_tools.sh \
    entry_bbr_management.sh \
    entry_docker_management.sh \
    entry_warp_management.sh \
    entry_network_test_suite.sh \
    entry_oracle_cloud_suite.sh \
    entry_ldnmp_site_suite.sh \
    entry_app_marketplace.sh \
    entry_workspace_suite.sh \
    entry_system_tools_suite.sh \
    entry_cluster_control_suite.sh \
    entry_uninstall.sh \
    entry_self_update.sh \
    entry_exit.sh; do
    assert_contains_fixed "$ENTRIES_LOAD_FILE" "$feature_file" "entries loader missing $feature_file"
  done

  assert_contains_fixed "$ROOT_DIR/modules/entry_basic_tools.sh" 'source "$ROOT_DIR/modules/luopo/basic_tools/menu.sh"' "basic tools entry should source LuoPo menu"
  assert_contains_fixed "$ROOT_DIR/modules/entry_basic_tools.sh" 'luopo_basic_tools_menu' "basic tools entry should call LuoPo menu"
  assert_contains_regex "$LUOPO_BASIC_TOOLS_MENU_FILE" '^luopo_basic_tools_menu\(\) \{' "missing LuoPo basic tools menu entry"
  assert_contains_regex "$LUOPO_BASIC_TOOLS_REGISTRY_FILE" '^LUOPO_BASIC_TOOLS_ITEMS=\(' "missing LuoPo basic tools registry"
  assert_contains_regex "$LUOPO_BASIC_TOOLS_ACTIONS_FILE" '^luopo_basic_tools_install_curl\(\) \{' "missing LuoPo basic tools action"
  assert_contains_regex "$LUOPO_BASIC_TOOLS_HELPERS_FILE" '^luopo_basic_tools_detect_package_manager\(\) \{' "missing LuoPo basic tools helper"
  assert_not_contains_fixed "$LUOPO_BASIC_TOOLS_HELPERS_FILE" 'ensure_luopo_vendor_loaded' "basic tools should no longer bootstrap vendor runtime"
  assert_contains_fixed "$ROOT_DIR/modules/entry_bbr_management.sh" 'source "$ROOT_DIR/modules/luopo/bbr_management/menu.sh"' "bbr entry should source LuoPo menu"
  assert_contains_fixed "$ROOT_DIR/modules/entry_bbr_management.sh" 'luopo_bbr_management_menu' "bbr entry should call LuoPo menu"
  assert_contains_regex "$LUOPO_BBR_MENU_FILE" '^luopo_bbr_management_menu\(\) \{' "missing LuoPo bbr menu entry"
  assert_not_contains_fixed "$LUOPO_BBR_HELPERS_FILE" 'ensure_luopo_vendor_loaded' "bbr should no longer bootstrap vendor runtime"
  assert_contains_regex "$LUOPO_BBR_ACTIONS_FILE" '^luopo_bbr_enable_alpine\(\) \{' "missing LuoPo bbr action"
  assert_contains_regex "$LUOPO_BBR_HELPERS_FILE" '^luopo_bbr_current_algorithms\(\) \{' "missing LuoPo bbr helper"
  assert_contains_fixed "$ROOT_DIR/modules/entry_docker_management.sh" 'source "$ROOT_DIR/modules/luopo/docker/manager.sh"' "docker entry should source LuoPo docker manager"
  assert_contains_fixed "$ROOT_DIR/modules/entry_docker_management.sh" 'docker_manager' "docker entry should call native docker manager"
  assert_contains_regex "$LUOPO_DOCKER_MANAGER_FILE" '^docker_manager\(\) \{' "missing LuoPo docker manager entry"
  assert_contains_fixed "$LUOPO_DOCKER_MANAGER_FILE" 'source "$LUOPO_DOCKER_PARTS_DIR/common.sh"' "docker manager should load common helpers"
  assert_contains_fixed "$LUOPO_DOCKER_MANAGER_FILE" 'source "$LUOPO_DOCKER_PARTS_DIR/install_status.sh"' "docker manager should load install/status actions"
  assert_contains_fixed "$LUOPO_DOCKER_MANAGER_FILE" 'source "$LUOPO_DOCKER_PARTS_DIR/resources.sh"' "docker manager should load resource menus"
  assert_contains_fixed "$LUOPO_DOCKER_MANAGER_FILE" 'source "$LUOPO_DOCKER_PARTS_DIR/daemon_backup.sh"' "docker manager should load daemon/backup actions"
  assert_contains_fixed "$ROOT_DIR/modules/entry_warp_management.sh" 'source "$ROOT_DIR/modules/luopo/warp_management/menu.sh"' "warp entry should source LuoPo menu"
  assert_contains_fixed "$ROOT_DIR/modules/entry_warp_management.sh" 'luopo_warp_management_menu' "warp entry should call LuoPo menu"
  assert_contains_regex "$LUOPO_WARP_MENU_FILE" '^luopo_warp_management_menu\(\) \{' "missing LuoPo warp menu entry"
  assert_contains_regex "$LUOPO_WARP_REGISTRY_FILE" '^LUOPO_WARP_ITEMS=\(' "missing LuoPo warp registry"
  assert_contains_regex "$LUOPO_WARP_ACTIONS_FILE" '^luopo_warp_launch_menu\(\) \{' "missing LuoPo warp action"
  assert_contains_regex "$LUOPO_WARP_HELPERS_FILE" '^luopo_warp_bootstrap\(\) \{' "missing LuoPo warp helper"
  assert_not_contains_fixed "$LUOPO_WARP_HELPERS_FILE" 'ensure_luopo_vendor_loaded' "warp should no longer bootstrap vendor runtime"
  assert_contains_fixed "$ROOT_DIR/modules/entry_network_test_suite.sh" 'source "$ROOT_DIR/modules/luopo/network_test/menu.sh"' "network test entry should source LuoPo menu"
  assert_contains_fixed "$ROOT_DIR/modules/entry_network_test_suite.sh" 'luopo_network_test_menu' "network test entry should call LuoPo menu"
  assert_contains_regex "$LUOPO_NETWORK_TEST_MENU_FILE" '^luopo_network_test_menu\(\) \{' "missing LuoPo network test menu entry"
  assert_contains_regex "$LUOPO_NETWORK_TEST_REGISTRY_FILE" '^LUOPO_NETWORK_TEST_ITEMS=\(' "missing LuoPo network test registry"
  assert_contains_regex "$LUOPO_NETWORK_TEST_ACTIONS_FILE" '^luopo_network_test_chatgpt_unlock\(\) \{' "missing LuoPo network test action"
  assert_contains_regex "$LUOPO_NETWORK_TEST_HELPERS_FILE" '^luopo_network_test_run_shell\(\) \{' "missing LuoPo network test helper"
  assert_not_contains_fixed "$LUOPO_NETWORK_TEST_HELPERS_FILE" 'ensure_luopo_vendor_loaded' "network test should no longer bootstrap vendor runtime"
  assert_contains_fixed "$ROOT_DIR/modules/entry_oracle_cloud_suite.sh" 'source "$ROOT_DIR/modules/luopo/oracle_cloud/menu.sh"' "oracle cloud entry should source LuoPo menu"
  assert_contains_fixed "$ROOT_DIR/modules/entry_oracle_cloud_suite.sh" 'luopo_oracle_cloud_menu' "oracle cloud entry should call LuoPo menu"
  assert_contains_regex "$LUOPO_ORACLE_CLOUD_MENU_FILE" '^luopo_oracle_cloud_menu\(\) \{' "missing LuoPo oracle cloud menu entry"
  assert_not_contains_fixed "$LUOPO_ORACLE_CLOUD_HELPERS_FILE" 'ensure_luopo_vendor_loaded' "oracle cloud should no longer bootstrap vendor runtime"
  assert_contains_regex "$LUOPO_ORACLE_CLOUD_REGISTRY_FILE" '^LUOPO_ORACLE_CLOUD_ITEMS=\(' "missing LuoPo oracle cloud registry"
  assert_contains_regex "$LUOPO_ORACLE_CLOUD_ACTIONS_FILE" '^luopo_oracle_cloud_install_lookbusy\(\) \{' "missing LuoPo oracle cloud action"
  assert_contains_regex "$LUOPO_ORACLE_CLOUD_HELPERS_FILE" '^luopo_oracle_cloud_run_shell\(\) \{' "missing LuoPo oracle cloud helper"
  assert_contains_fixed "$ROOT_DIR/modules/entry_ldnmp_site_suite.sh" 'source "$ROOT_DIR/modules/luopo/ldnmp/menu.sh"' "ldnmp entry should source LuoPo menu"
  assert_contains_fixed "$ROOT_DIR/modules/entry_ldnmp_site_suite.sh" 'luopo_ldnmp_menu' "ldnmp entry should call LuoPo menu"
  assert_contains_regex "$LUOPO_LDNMP_MENU_FILE" '^luopo_ldnmp_menu\(\) \{' "missing LuoPo ldnmp menu entry"
  assert_contains_regex "$LUOPO_LDNMP_MENU_FILE" '^luopo_render_ldnmp_menu\(\) \{' "missing LuoPo ldnmp render menu"
  assert_contains_fixed "$LUOPO_LDNMP_MENU_FILE" 'read -r -p "请输入你的选择: " sub_choice' "ldnmp should read choice in LuoPo menu"
  assert_contains_regex "$LUOPO_LDNMP_REGISTRY_FILE" '^LUOPO_LDNMP_ITEMS=\(' "missing LuoPo ldnmp registry"
  assert_contains_regex "$LUOPO_LDNMP_REGISTRY_FILE" '^LUOPO_LDNMP_LAYOUT=\(' "missing LuoPo ldnmp layout registry"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_FILE" '^luopo_ldnmp_dispatch_choice\(\) \{' "missing LuoPo ldnmp dispatch action"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" 'source "$LUOPO_LDNMP_DIR/actions_sites.sh"' "ldnmp dispatch should source site actions"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" 'source "$LUOPO_LDNMP_DIR/actions_proxy.sh"' "ldnmp dispatch should source proxy actions"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_PROXY_FILE" 'source "$LUOPO_LDNMP_DIR/actions_proxy_core.sh"' "ldnmp proxy loader should source core proxy actions"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_PROXY_FILE" 'source "$LUOPO_LDNMP_DIR/actions_stream.sh"' "ldnmp proxy loader should source stream actions"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_PROXY_FILE" 'source "$LUOPO_LDNMP_DIR/actions_site_status.sh"' "ldnmp proxy loader should source site status actions"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_PROXY_FILE" 'source "$LUOPO_LDNMP_DIR/actions_security.sh"' "ldnmp proxy loader should source security actions"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_PROXY_FILE" 'source "$LUOPO_LDNMP_DIR/actions_optimization.sh"' "ldnmp proxy loader should source optimization actions"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" 'source "$LUOPO_LDNMP_DIR/actions_maintenance.sh"' "ldnmp dispatch should source maintenance actions"
  assert_not_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '[[ "$choice" == "0" ]] || luopo_ldnmp_require_vendor_runtime || return 1' "ldnmp dispatch should not globally load legacy runtime"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '1) luopo_ldnmp_install_all ;;' "ldnmp should route install-all directly"
  assert_not_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" 'run_luopo_compat_menu linux_ldnmp' "ldnmp should no longer route through compat"
  assert_not_contains_fixed "$LUOPO_LDNMP_REGISTRY_FILE" 'luopo_ldnmp_launch_compat' "ldnmp registry should no longer contain compat actions"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_install_discuz\(\) \{' "missing ldnmp discuz action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_install_kodbox\(\) \{' "missing ldnmp kodbox action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_install_maccms\(\) \{' "missing ldnmp maccms action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_install_dujiaoka\(\) \{' "missing ldnmp dujiaoka action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_install_flarum\(\) \{' "missing ldnmp flarum action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_install_typecho\(\) \{' "missing ldnmp typecho action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_install_linkstack\(\) \{' "missing ldnmp linkstack action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_custom_dynamic_site\(\) \{' "missing ldnmp custom dynamic site action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_PROXY_CORE_FILE" '^luopo_ldnmp_redirect_site\(\) \{' "missing ldnmp redirect action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_PROXY_CORE_FILE" '^luopo_ldnmp_reverse_proxy_domain\(\) \{' "missing ldnmp domain proxy action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_PROXY_CORE_FILE" '^luopo_ldnmp_reverse_proxy_load_balance\(\) \{' "missing ldnmp load-balance proxy action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_STREAM_FILE" '^luopo_ldnmp_stream_proxy\(\) \{' "missing ldnmp stream proxy action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITE_STATUS_FILE" '^luopo_ldnmp_site_status\(\) \{' "missing ldnmp site status action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SECURITY_FILE" '^luopo_ldnmp_security\(\) \{' "missing ldnmp security action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_OPTIMIZATION_FILE" '^luopo_ldnmp_optimization\(\) \{' "missing ldnmp optimization action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_install_bitwarden\(\) \{' "missing ldnmp bitwarden action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_install_halo\(\) \{' "missing ldnmp halo action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_install_ai_prompt_generator\(\) \{' "missing ldnmp ai prompt action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_SITES_FILE" '^luopo_ldnmp_custom_static_site\(\) \{' "missing ldnmp static site action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_MAINTENANCE_FILE" '^luopo_ldnmp_backup_all\(\) \{' "missing ldnmp backup action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_MAINTENANCE_FILE" '^luopo_ldnmp_scheduled_remote_backup\(\) \{' "missing ldnmp scheduled backup action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_MAINTENANCE_FILE" '^luopo_ldnmp_restore_all\(\) \{' "missing ldnmp restore action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_MAINTENANCE_FILE" '^luopo_ldnmp_update_menu\(\) \{' "missing ldnmp update action"
  assert_contains_regex "$LUOPO_LDNMP_ACTIONS_MAINTENANCE_FILE" '^luopo_ldnmp_uninstall\(\) \{' "missing ldnmp uninstall action"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '3) luopo_ldnmp_install_discuz ;;' "ldnmp should route discuz directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '4) luopo_ldnmp_install_kodbox ;;' "ldnmp should route kodbox directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '5) luopo_ldnmp_install_maccms ;;' "ldnmp should route maccms directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '6) luopo_ldnmp_install_dujiaoka ;;' "ldnmp should route dujiaoka directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '7) luopo_ldnmp_install_flarum ;;' "ldnmp should route flarum directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '8) luopo_ldnmp_install_typecho ;;' "ldnmp should route typecho directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '9) luopo_ldnmp_install_linkstack ;;' "ldnmp should route linkstack directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '10) luopo_ldnmp_custom_dynamic_site ;;' "ldnmp should route custom dynamic site directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '22) luopo_ldnmp_redirect_site ;;' "ldnmp should route redirect directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '23) luopo_ldnmp_reverse_proxy_ip_port ;;' "ldnmp should route ip-port proxy directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '24) luopo_ldnmp_reverse_proxy_domain ;;' "ldnmp should route domain proxy directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '25) luopo_ldnmp_install_bitwarden ;;' "ldnmp should route bitwarden directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '26) luopo_ldnmp_install_halo ;;' "ldnmp should route halo directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '27) luopo_ldnmp_install_ai_prompt_generator ;;' "ldnmp should route ai prompt directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '30) luopo_ldnmp_custom_static_site ;;' "ldnmp should route static site directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '31) luopo_ldnmp_site_status ;;' "ldnmp should route site status directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '32) luopo_ldnmp_backup_all ;;' "ldnmp should route backup directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '33) luopo_ldnmp_scheduled_remote_backup ;;' "ldnmp should route scheduled backup directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '34) luopo_ldnmp_restore_all ;;' "ldnmp should route restore directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '35) luopo_ldnmp_security ;;' "ldnmp should route security directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '36) luopo_ldnmp_optimization ;;' "ldnmp should route optimization directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '37) luopo_ldnmp_update_menu ;;' "ldnmp should route update directly"
  assert_contains_fixed "$LUOPO_LDNMP_ACTIONS_FILE" '38) luopo_ldnmp_uninstall ;;' "ldnmp should route uninstall directly"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_FILE" '^luopo_ldnmp_bootstrap\(\) \{' "missing LuoPo ldnmp helper"
  assert_contains_fixed "$LUOPO_LDNMP_HELPERS_FILE" 'luopo_ldnmp_bootstrap() {' "ldnmp should define native bootstrap"
  assert_contains_fixed "$LUOPO_LDNMP_HELPERS_FILE" 'source "$LUOPO_LDNMP_DIR/helpers_install.sh"' "ldnmp helpers should source install helpers"
  assert_contains_fixed "$LUOPO_LDNMP_HELPERS_FILE" 'source "$LUOPO_LDNMP_DIR/helpers_runtime.sh"' "ldnmp helpers should source runtime helpers"
  assert_contains_fixed "$LUOPO_LDNMP_HELPERS_FILE" 'source "$LUOPO_LDNMP_DIR/helpers_site.sh"' "ldnmp helpers should source site helpers"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_INSTALL_FILE" '^install_dependency\(\) \{' "ldnmp should define native dependency installer"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_INSTALL_FILE" '^install_ldnmp_conf\(\) \{' "ldnmp should define native compose config installer"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_INSTALL_FILE" '^install_ldnmp\(\) \{' "ldnmp should define native environment installer"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_INSTALL_FILE" '^install_certbot\(\) \{' "ldnmp should define native certbot scheduler"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_INSTALL_FILE" '^nginx_upgrade\(\) \{' "ldnmp should define native nginx updater"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_INSTALL_FILE" '^patch_wp_url\(\) \{' "ldnmp should define native wordpress url patcher"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_RUNTIME_FILE" '^ldnmp_v\(\) \{' "ldnmp should define native version status helper"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_RUNTIME_FILE" '^luopo_ldnmp_render_status_banner\(\) \{' "ldnmp should define native status banner"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_SITE_FILE" '^nginx_http_on\(\) \{' "ldnmp should define native nginx http helper"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_RUNTIME_FILE" '^save_iptables_rules\(\) \{' "ldnmp should define native iptables persistence helper"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_RUNTIME_FILE" '^check_crontab_installed\(\) \{' "ldnmp should define native crontab helper"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_SITE_FILE" '^add_yuming\(\) \{' "ldnmp should define native domain prompt helper"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_SITE_FILE" '^repeat_add_yuming\(\) \{' "ldnmp should define native repeated domain cleanup helper"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_SITE_FILE" '^install_ssltls\(\) \{' "ldnmp should define native cert install helper"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_SITE_FILE" '^certs_status\(\) \{' "ldnmp should define native cert status helper"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_SITE_FILE" '^luopo_ldnmp_proxy_site\(\) \{' "ldnmp should define native reverse proxy helper"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_SITE_FILE" '^check_docker_image_update\(\) \{' "ldnmp should define native docker update checker"
  assert_not_contains_fixed "$LUOPO_LDNMP_HELPERS_FILE" 'legacy_bridge.sh' "ldnmp helpers should not source legacy bridge"
  assert_not_contains_fixed "$LUOPO_LDNMP_HELPERS_FILE" 'luopo_ldnmp_require_vendor_runtime() {' "ldnmp helpers should not keep vendor loader inline"
  assert_contains_regex "$LUOPO_LDNMP_HELPERS_FILE" '^luopo_ldnmp_render_cell\(\) \{' "missing LuoPo ldnmp render helper"
  assert_contains_fixed "$LUOPO_LDNMP_MENU_FILE" 'luopo_ldnmp_render_status_banner' "ldnmp menu should render status banner through helper"
  assert_not_contains_fixed "$LUOPO_LDNMP_MENU_FILE" 'luopo_print_two_column_cells' "ldnmp should render as single column"
  assert_contains_fixed "$ROOT_DIR/modules/entry_workspace_suite.sh" 'source "$ROOT_DIR/modules/luopo/workspace/menu.sh"' "workspace entry should source LuoPo menu"
  assert_contains_fixed "$ROOT_DIR/modules/entry_workspace_suite.sh" 'luopo_workspace_menu' "workspace entry should call LuoPo menu"
  assert_contains_regex "$LUOPO_WORKSPACE_MENU_FILE" '^luopo_workspace_menu\(\) \{' "missing LuoPo workspace menu entry"
  assert_not_contains_fixed "$LUOPO_WORKSPACE_HELPERS_FILE" 'ensure_luopo_vendor_loaded' "workspace should no longer bootstrap vendor runtime"
  assert_contains_regex "$LUOPO_WORKSPACE_REGISTRY_FILE" '^LUOPO_WORKSPACE_ITEMS=\(' "missing LuoPo workspace registry"
  assert_contains_regex "$LUOPO_WORKSPACE_ACTIONS_FILE" '^luopo_workspace_manage_ssh_mode\(\) \{' "missing LuoPo workspace action"
  assert_contains_regex "$LUOPO_WORKSPACE_HELPERS_FILE" '^luopo_workspace_run_named_session\(\) \{' "missing LuoPo workspace helper"
  assert_contains_fixed "$ROOT_DIR/modules/entry_cluster_control_suite.sh" 'source "$ROOT_DIR/modules/luopo/cluster_control/menu.sh"' "cluster entry should source LuoPo menu"
  assert_contains_fixed "$ROOT_DIR/modules/entry_cluster_control_suite.sh" 'luopo_cluster_control_menu' "cluster entry should call LuoPo menu"
  assert_contains_regex "$LUOPO_CLUSTER_MENU_FILE" '^luopo_cluster_control_menu\(\) \{' "missing LuoPo cluster menu entry"
  assert_contains_regex "$LUOPO_CLUSTER_REGISTRY_FILE" '^LUOPO_CLUSTER_ITEMS=\(' "missing LuoPo cluster registry"
  assert_contains_regex "$LUOPO_CLUSTER_ACTIONS_FILE" '^luopo_cluster_install_toolkit\(\) \{' "missing LuoPo cluster action"
  assert_contains_regex "$LUOPO_CLUSTER_HELPERS_FILE" '^luopo_cluster_bootstrap\(\) \{' "missing LuoPo cluster helper"
  assert_not_contains_fixed "$LUOPO_CLUSTER_HELPERS_FILE" 'ensure_luopo_vendor_loaded' "cluster control should no longer bootstrap vendor runtime"
  assert_contains_regex "$LUOPO_CLUSTER_HELPERS_FILE" '^luopo_cluster_run_commands_on_servers\(\) \{' "cluster control should define native remote runner"
  assert_contains_fixed "$ROOT_DIR/modules/entry_app_marketplace.sh" 'source "$ROOT_DIR/modules/luopo/app_marketplace/menu.sh"' "app market entry should source LuoPo menu"
  assert_contains_fixed "$ROOT_DIR/modules/entry_app_marketplace.sh" 'luopo_app_marketplace_menu' "app market entry should call LuoPo menu"
  assert_contains_regex "$LUOPO_APP_MARKET_MENU_FILE" '^luopo_app_marketplace_menu\(\) \{' "missing LuoPo app market menu entry"
  assert_contains_regex "$LUOPO_APP_MARKET_REGISTRY_FILE" '^LUOPO_APP_MARKETPLACE_ITEMS=\(' "missing LuoPo app market registry"
  assert_contains_regex "$LUOPO_APP_MARKET_REGISTRY_FILE" '^LUOPO_APP_MARKETPLACE_LAYOUT=\(' "missing LuoPo app market layout registry"
  assert_contains_fixed "$LUOPO_APP_MARKET_REGISTRY_FILE" '"##|面板与运维管理"' "app market should render category headings"
  assert_contains_fixed "$LUOPO_APP_MARKET_MENU_FILE" 'if [[ "$row" == "##|"* ]]; then' "app market menu should support category headings"
  assert_contains_fixed "$LUOPO_APP_MARKET_MENU_FILE" 'echo -e "${gl_kjlan}[ ${title} ]${gl_bai}"' "app market category headings should use bracket style"
  assert_contains_regex "$LUOPO_APP_MARKET_ACTIONS_FILE" '^luopo_app_marketplace_dispatch_choice\(\) \{' "missing LuoPo app market dispatch action"
  assert_contains_regex "$LUOPO_APP_MARKET_ACTIONS_FILE" '^luopo_app_marketplace_backup_all\(\) \{' "missing native app market backup action"
  assert_contains_regex "$LUOPO_APP_MARKET_ACTIONS_FILE" '^luopo_app_marketplace_restore_all\(\) \{' "missing native app market restore action"
  assert_contains_regex "$LUOPO_APP_MARKET_HELPERS_FILE" '^luopo_app_marketplace_bootstrap\(\) \{' "missing LuoPo app market helper"
  assert_contains_regex "$LUOPO_APP_MARKET_HELPERS_FILE" '^luopo_app_marketplace_sync_index\(\) \{' "missing LuoPo app market sync helper"
  assert_contains_regex "$LUOPO_APP_MARKET_HELPERS_FILE" '^luopo_app_marketplace_render_cell\(\) \{' "missing LuoPo app market render helper"
  assert_contains_fixed "$LUOPO_APP_MARKET_HELPERS_FILE" 'source "$ROOT_DIR/modules/luopo/ldnmp/helpers.sh"' "app market helpers should source native ldnmp helpers"
  assert_not_contains_fixed "$LUOPO_APP_MARKET_HELPERS_FILE" 'legacy_bridge.sh' "app market helpers should not source legacy bridge"
  assert_native_contains_fixed 'luopo_ldnmp_proxy_site "${yuming}" 127.0.0.1 "${app_port}"' "app market should use native ldnmp proxy helper"
  assert_contains_regex "$LUOPO_APP_MARKET_MENU_FILE" '^luopo_render_app_marketplace_menu\(\) \{' "missing LuoPo app market render menu"
  assert_contains_fixed "$LUOPO_APP_MARKET_MENU_FILE" 'read -r -p "请输入你的选择: " sub_choice' "app market should read choice in LuoPo menu"
  assert_contains_fixed "$LUOPO_APP_MARKET_REGISTRY_FILE" '"91|备份全部应用数据"' "app market should keep backup action"
  assert_contains_fixed "$LUOPO_APP_MARKET_REGISTRY_FILE" '"92|还原全部应用数据"' "app market should keep restore action"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_backup_all' "app market should route backup action"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_restore_all' "app market should route restore action"
  assert_not_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'run_luopo_compat_menu linux_panel' "app market should no longer route selected apps through compat"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_onepanel_menu' "app market dispatch should route 1panel natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_npm_menu' "app market dispatch should route npm natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_openlist_menu' "app market dispatch should route openlist natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_nezha_menu' "app market dispatch should route nezha natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_qinglong_menu' "app market dispatch should route qinglong natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_adguardhome_menu' "app market dispatch should route adguardhome natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_safeline_menu' "app market dispatch should route safeline natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_portainer_menu' "app market dispatch should route portainer natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_vscode_menu' "app market dispatch should route vscode natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_uptime_kuma_menu' "app market dispatch should route uptime kuma natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_memos_menu' "app market dispatch should route memos natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_dockge_menu' "app market dispatch should route dockge natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_librespeed_menu' "app market dispatch should route librespeed natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_searxng_menu' "app market dispatch should route searxng natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_stirling_pdf_menu' "app market dispatch should route stirling pdf natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_drawio_menu' "app market dispatch should route drawio natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_myip_menu' "app market dispatch should route myip natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_rustdesk_hbbs_menu' "app market dispatch should route rustdesk server natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_rustdesk_hbbr_menu' "app market dispatch should route rustdesk relay natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_frps_menu' "app market dispatch should route frps natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_frpc_menu' "app market dispatch should route frpc natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_REGISTRY_FILE" '"26|FRP内网穿透(服务端)"' "app market frps should keep adjacent app number"
  assert_contains_fixed "$LUOPO_APP_MARKET_REGISTRY_FILE" '"27|FRP内网穿透(客户端)"' "app market frpc should keep adjacent app number"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" '27)' "app market dispatch should route frpc from adjacent app number"
  assert_native_contains_fixed 'luopo_app_marketplace_native_add_app_id "27"' "frpc installed-state marker should use adjacent app number"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_dify_menu' "app market dispatch should route dify natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_newapi_menu' "app market dispatch should route newapi natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_openwebui_menu' "app market dispatch should route openwebui natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_it_tools_menu' "app market dispatch should route it-tools natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_n8n_menu' "app market dispatch should route n8n natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_ddns_go_menu' "app market dispatch should route ddns-go natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_allinssl_menu' "app market dispatch should route allinssl natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_navidrome_menu' "app market dispatch should route navidrome natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_bitwarden_menu' "app market dispatch should route bitwarden natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_gpt_load_menu' "app market dispatch should route gpt-load natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_beszel_menu' "app market dispatch should route beszel natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_linkwarden_menu' "app market dispatch should route linkwarden natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_komari_menu' "app market dispatch should route komari natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_immich_menu' "app market dispatch should route immich natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_jellyfin_menu' "app market dispatch should route jellyfin natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_gitea_menu' "app market dispatch should route gitea natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_filebrowser_menu' "app market dispatch should route filebrowser natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_dufs_menu' "app market dispatch should route dufs natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_paperless_menu' "app market dispatch should route paperless natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_syncthing_menu' "app market dispatch should route syncthing natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_umami_menu' "app market dispatch should route umami natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_siyuan_menu' "app market dispatch should route siyuan natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_zfile_menu' "app market dispatch should route zfile natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_karakeep_menu' "app market dispatch should route karakeep natively"
  assert_contains_fixed "$LUOPO_APP_MARKET_ACTIONS_FILE" 'luopo_app_marketplace_lucky_menu' "app market dispatch should route lucky natively"
  assert_native_contains_regex '^luopo_app_marketplace_native_docker_app_menu\(\) \{' "missing native docker app menu helper"
  assert_native_contains_regex '^luopo_app_marketplace_native_container_action_menu\(\) \{' "missing native container app menu helper"
  assert_native_contains_regex '^luopo_app_marketplace_onepanel_menu\(\) \{' "missing native 1panel menu"
  assert_native_contains_regex '^luopo_app_marketplace_npm_menu\(\) \{' "missing native npm menu"
  assert_native_contains_regex '^luopo_app_marketplace_openlist_menu\(\) \{' "missing native openlist menu"
  assert_native_contains_regex '^luopo_app_marketplace_nezha_menu\(\) \{' "missing native nezha menu"
  assert_native_contains_regex '^luopo_app_marketplace_qinglong_menu\(\) \{' "missing native qinglong menu"
  assert_native_contains_regex '^luopo_app_marketplace_adguardhome_menu\(\) \{' "missing native adguardhome menu"
  assert_native_contains_regex '^luopo_app_marketplace_safeline_menu\(\) \{' "missing native safeline menu"
  assert_native_contains_regex '^luopo_app_marketplace_portainer_menu\(\) \{' "missing native portainer menu"
  assert_native_contains_regex '^luopo_app_marketplace_vscode_menu\(\) \{' "missing native vscode menu"
  assert_native_contains_regex '^luopo_app_marketplace_uptime_kuma_menu\(\) \{' "missing native uptime kuma menu"
  assert_native_contains_regex '^luopo_app_marketplace_memos_menu\(\) \{' "missing native memos menu"
  assert_native_contains_regex '^luopo_app_marketplace_dockge_menu\(\) \{' "missing native dockge menu"
  assert_native_contains_regex '^luopo_app_marketplace_librespeed_menu\(\) \{' "missing native librespeed menu"
  assert_native_contains_regex '^luopo_app_marketplace_searxng_menu\(\) \{' "missing native searxng menu"
  assert_native_contains_regex '^luopo_app_marketplace_stirling_pdf_menu\(\) \{' "missing native stirling pdf menu"
  assert_native_contains_regex '^luopo_app_marketplace_drawio_menu\(\) \{' "missing native drawio menu"
  assert_native_contains_regex '^luopo_app_marketplace_myip_menu\(\) \{' "missing native myip menu"
  assert_native_contains_regex '^luopo_app_marketplace_rustdesk_hbbs_menu\(\) \{' "missing native rustdesk server menu"
  assert_native_contains_regex '^luopo_app_marketplace_rustdesk_hbbr_menu\(\) \{' "missing native rustdesk relay menu"
  assert_native_contains_regex '^luopo_app_marketplace_frps_menu\(\) \{' "missing native frps menu"
  assert_native_contains_regex '^luopo_app_marketplace_frpc_menu\(\) \{' "missing native frpc menu"
  assert_native_contains_regex '^luopo_app_marketplace_dify_menu\(\) \{' "missing native dify menu"
  assert_native_contains_regex '^luopo_app_marketplace_newapi_menu\(\) \{' "missing native newapi menu"
  assert_native_contains_regex '^luopo_app_marketplace_openwebui_menu\(\) \{' "missing native openwebui menu"
  assert_native_contains_regex '^luopo_app_marketplace_it_tools_menu\(\) \{' "missing native it-tools menu"
  assert_native_contains_regex '^luopo_app_marketplace_n8n_menu\(\) \{' "missing native n8n menu"
  assert_native_contains_regex '^luopo_app_marketplace_ddns_go_menu\(\) \{' "missing native ddns-go menu"
  assert_native_contains_regex '^luopo_app_marketplace_allinssl_menu\(\) \{' "missing native allinssl menu"
  assert_native_contains_regex '^luopo_app_marketplace_navidrome_menu\(\) \{' "missing native navidrome menu"
  assert_native_contains_regex '^luopo_app_marketplace_bitwarden_menu\(\) \{' "missing native bitwarden menu"
  assert_native_contains_regex '^luopo_app_marketplace_gpt_load_menu\(\) \{' "missing native gpt-load menu"
  assert_native_contains_regex '^luopo_app_marketplace_beszel_menu\(\) \{' "missing native beszel menu"
  assert_native_contains_regex '^luopo_app_marketplace_linkwarden_menu\(\) \{' "missing native linkwarden menu"
  assert_native_contains_regex '^luopo_app_marketplace_komari_menu\(\) \{' "missing native komari menu"
  assert_native_contains_regex '^luopo_app_marketplace_immich_menu\(\) \{' "missing native immich menu"
  assert_native_contains_regex '^luopo_app_marketplace_jellyfin_menu\(\) \{' "missing native jellyfin menu"
  assert_native_contains_regex '^luopo_app_marketplace_gitea_menu\(\) \{' "missing native gitea menu"
  assert_native_contains_regex '^luopo_app_marketplace_filebrowser_menu\(\) \{' "missing native filebrowser menu"
  assert_native_contains_regex '^luopo_app_marketplace_dufs_menu\(\) \{' "missing native dufs menu"
  assert_native_contains_regex '^luopo_app_marketplace_paperless_menu\(\) \{' "missing native paperless menu"
  assert_native_contains_regex '^luopo_app_marketplace_syncthing_menu\(\) \{' "missing native syncthing menu"
  assert_native_contains_regex '^luopo_app_marketplace_umami_menu\(\) \{' "missing native umami menu"
  assert_native_contains_regex '^luopo_app_marketplace_siyuan_menu\(\) \{' "missing native siyuan menu"
  assert_native_contains_regex '^luopo_app_marketplace_zfile_menu\(\) \{' "missing native zfile menu"
  assert_native_contains_regex '^luopo_app_marketplace_karakeep_menu\(\) \{' "missing native karakeep menu"
  assert_native_contains_regex '^luopo_app_marketplace_lucky_menu\(\) \{' "missing native lucky menu"
  assert_contains_fixed "$ROOT_DIR/modules/entry_system_tools_suite.sh" 'source "$ROOT_DIR/modules/luopo/system_tools/menu.sh"' "system tools entry should source LuoPo menu"
  assert_contains_fixed "$ROOT_DIR/modules/entry_system_tools_suite.sh" 'luopo_system_tools_menu' "system tools entry should call LuoPo menu"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_MENU_FILE" '^luopo_system_tools_menu\(\) \{' "missing LuoPo system tools menu entry"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_MENU_FILE" '^luopo_render_system_tools_menu\(\) \{' "missing LuoPo system tools render menu"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_MENU_FILE" 'read -r -p "请输入你的选择: " sub_choice' "system tools should read choice in LuoPo menu"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_REGISTRY_FILE" '^LUOPO_SYSTEM_TOOLS_ITEMS=\(' "missing LuoPo system tools registry"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_REGISTRY_FILE" '^LUOPO_SYSTEM_TOOLS_LAYOUT=\(' "missing LuoPo system tools layout registry"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '^luopo_system_tools_dispatch_choice\(\) \{' "missing LuoPo system tools dispatch action"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" 'source "$LUOPO_SYSTEM_TOOLS_DIR/actions_access.sh"' "system tools dispatch should source access actions"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" 'source "$LUOPO_SYSTEM_TOOLS_DIR/actions_operations.sh"' "system tools dispatch should source operations actions"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" 'source "$LUOPO_SYSTEM_TOOLS_DIR/actions_misc.sh"' "system tools dispatch should source misc actions"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_ACCESS_FILE" '^luopo_system_tools_python_version_menu\(\) \{' "missing LuoPo system tools python version action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_ACCESS_FILE" '^luopo_system_tools_modify_ssh_port_menu\(\) \{' "missing LuoPo system tools ssh port action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_ACCESS_FILE" '^luopo_system_tools_disable_root_create_user\(\) \{' "missing LuoPo system tools disable root action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_ACCESS_FILE" '^luopo_system_tools_swap_menu\(\) \{' "missing LuoPo system tools swap action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_ACCESS_FILE" '^luopo_system_tools_network_priority_menu\(\) \{' "missing LuoPo system tools network priority action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_ACCESS_FILE" '^luopo_system_tools_show_ports\(\) \{' "missing LuoPo system tools port status action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_ACCESS_FILE" '^luopo_system_tools_user_management_menu\(\) \{' "missing LuoPo system tools user management action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_ACCESS_FILE" '^luopo_system_tools_iptables_menu\(\) \{' "missing LuoPo system tools firewall action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_ACCESS_FILE" '^luopo_system_tools_sshkey_menu\(\) \{' "missing LuoPo system tools ssh key action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_change_hostname_menu\(\) \{' "missing LuoPo system tools hostname action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_switch_mirror_menu\(\) \{' "missing LuoPo system tools mirror switch action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_crontab_menu\(\) \{' "missing LuoPo system tools crontab action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_hosts_menu\(\) \{' "missing LuoPo system tools hosts action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_traffic_shutdown_menu\(\) \{' "missing LuoPo system tools traffic shutdown action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_tg_monitor_menu\(\) \{' "missing LuoPo system tools tg monitor action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_dns_menu\(\) \{' "missing LuoPo system tools dns action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_fail2ban_menu\(\) \{' "missing LuoPo system tools fail2ban action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_network_card_menu\(\) \{' "missing LuoPo system tools network card action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_log_menu\(\) \{' "missing LuoPo system tools log action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_env_menu\(\) \{' "missing LuoPo system tools env action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_shell_theme_menu\(\) \{' "missing LuoPo system tools shell theme action"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_ACTIONS_OPERATIONS_FILE" '^luopo_system_tools_language_menu\(\) \{' "missing LuoPo system tools language action"
  assert_system_misc_contains_regex '^luopo_system_tools_fix_openssh\(\) \{' "missing LuoPo system tools openssh fix action"
  assert_system_misc_contains_regex '^luopo_system_tools_one_click_tune\(\) \{' "missing LuoPo system tools one-click tune action"
  assert_system_misc_contains_regex '^luopo_system_tools_history_menu\(\) \{' "missing LuoPo system tools history action"
  assert_system_misc_contains_regex '^luopo_system_tools_command_favorites\(\) \{' "missing LuoPo system tools command favorites action"
  assert_system_misc_contains_regex '^luopo_system_tools_backup_menu\(\) \{' "missing LuoPo system tools backup action"
  assert_system_misc_contains_regex '^luopo_system_tools_trash_menu\(\) \{' "missing LuoPo system tools trash action"
  assert_system_misc_contains_regex '^luopo_system_tools_file_menu\(\) \{' "missing LuoPo system tools file action"
  assert_system_misc_contains_regex '^luopo_system_tools_rsync_menu\(\) \{' "missing LuoPo system tools rsync action"
  assert_system_misc_contains_regex '^luopo_system_tools_rsync_run_task\(\) \{' "missing LuoPo system tools rsync runner"
  assert_system_misc_contains_regex '^luopo_system_tools_clamav_menu\(\) \{' "missing LuoPo system tools clamav action"
  assert_system_misc_contains_regex '^luopo_system_tools_ssh_manager_menu\(\) \{' "missing LuoPo system tools ssh manager action"
  assert_system_misc_contains_regex '^luopo_system_tools_disk_manager_menu\(\) \{' "missing LuoPo system tools disk manager action"
  assert_system_misc_contains_regex '^luopo_system_tools_reinstall_menu\(\) \{' "missing LuoPo system tools reinstall action"
  assert_system_misc_contains_regex '^luopo_system_tools_elrepo_menu\(\) \{' "missing LuoPo system tools elrepo action"
  assert_system_misc_contains_regex '^luopo_system_tools_kernel_optimize_menu\(\) \{' "missing LuoPo system tools kernel optimize action"
  assert_system_misc_contains_regex '^luopo_system_tools_generate_credentials\(\) \{' "missing LuoPo system tools credential generator action"
  assert_system_misc_contains_regex '^luopo_system_tools_timezone_menu\(\) \{' "missing LuoPo system tools timezone action"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" 'source "$ROOT_DIR/modules/luopo/bbr_management/menu.sh"' "system tools should source native BBR menu"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '16) luopo_bbr_management_menu ;;' "system tools should route BBR shortcut natively"
  assert_not_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" 'run_luopo_compat_menu linux_bbr' "system tools should not route BBR shortcut through compat"
  assert_not_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" 'run_luopo_compat_menu linux_Settings' "system tools should not fall back to full compat settings menu"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '10) luopo_system_tools_network_priority_menu ;;' "system tools dispatch should route network priority natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '4) luopo_system_tools_python_version_menu ;;' "system tools dispatch should route python manager natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '6) luopo_system_tools_modify_ssh_port_menu ;;' "system tools dispatch should route ssh port natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '9) luopo_system_tools_disable_root_create_user ;;' "system tools dispatch should route root disable natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '11) luopo_system_tools_show_ports ;;' "system tools dispatch should route port status natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '13) luopo_system_tools_user_management_menu ;;' "system tools dispatch should route user management natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '18) luopo_system_tools_change_hostname_menu ;;' "system tools dispatch should route hostname natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '19) luopo_system_tools_switch_mirror_menu ;;' "system tools dispatch should route mirror switching natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '20) luopo_system_tools_crontab_menu ;;' "system tools dispatch should route crontab natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '21) luopo_system_tools_hosts_menu ;;' "system tools dispatch should route hosts natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '22) luopo_system_tools_fail2ban_menu ;;' "system tools dispatch should route fail2ban natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '23) luopo_system_tools_traffic_shutdown_menu ;;' "system tools dispatch should route traffic shutdown natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '25) luopo_system_tools_tg_monitor_menu ;;' "system tools dispatch should route tg monitor natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '26) luopo_system_tools_fix_openssh ;;' "system tools dispatch should route openssh fix natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '8) luopo_system_tools_reinstall_menu ;;' "system tools dispatch should route reinstall natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '27) luopo_system_tools_elrepo_menu ;;' "system tools dispatch should route elrepo natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '28) luopo_system_tools_kernel_optimize_menu ;;' "system tools dispatch should route kernel optimization natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '29) luopo_system_tools_clamav_menu ;;' "system tools dispatch should route clamav natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '30) luopo_system_tools_file_menu ;;' "system tools dispatch should route file manager natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '31) luopo_system_tools_language_menu ;;' "system tools dispatch should route language menu natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '32) luopo_system_tools_shell_theme_menu ;;' "system tools dispatch should route shell beautify natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '33) luopo_system_tools_trash_menu ;;' "system tools dispatch should route trash menu natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '34) luopo_system_tools_backup_menu ;;' "system tools dispatch should route backup menu natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '35) luopo_system_tools_ssh_manager_menu ;;' "system tools dispatch should route ssh manager natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '36) luopo_system_tools_disk_manager_menu ;;' "system tools dispatch should route disk manager natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '37) luopo_system_tools_history_menu ;;' "system tools dispatch should route history natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '38) luopo_system_tools_rsync_menu ;;' "system tools dispatch should route rsync menu natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '39) luopo_system_tools_command_favorites ;;' "system tools dispatch should route favorites natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '40) luopo_system_tools_network_card_menu ;;' "system tools dispatch should route nic manager natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '41) luopo_system_tools_log_menu ;;' "system tools dispatch should route log manager natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '42) luopo_system_tools_env_menu ;;' "system tools dispatch should route env manager natively"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_ACTIONS_FILE" '62) luopo_system_tools_one_click_tune ;;' "system tools dispatch should route one-click tuning natively"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^luopo_system_tools_bootstrap\(\) \{' "missing LuoPo system tools helper"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" 'luopo_system_tools_bootstrap() {' "system tools should define native bootstrap"
  assert_contains_fixed "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" 'return 0' "system tools bootstrap should default to native path"
  assert_not_contains_fixed "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" 'legacy_bridge.sh' "system tools helpers should not source legacy bridge"
  assert_not_contains_fixed "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" 'luopo_system_tools_run_vendor_function() {' "system tools helpers should not keep vendor runner inline"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^root_use\(\) \{' "system tools should define native root helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^check_crontab_installed\(\) \{' "system tools should define native crontab helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^prefer_ipv4\(\) \{' "system tools should define native network priority helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^restart_ssh\(\) \{' "system tools should define native ssh restart helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^current_timezone\(\) \{' "system tools should define native timezone reader"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^set_timedate\(\) \{' "system tools should define native timezone setter"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^save_iptables_rules\(\) \{' "system tools should define native iptables persistence helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^iptables_open\(\) \{' "system tools should define native open-all-ports helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^open_port\(\) \{' "system tools should define native open-port helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^close_port\(\) \{' "system tools should define native close-port helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^correct_ssh_config\(\) \{' "system tools should define native ssh config repair helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^new_ssh_port\(\) \{' "system tools should define native ssh port helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^add_swap\(\) \{' "system tools should define native swap helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^luopo_system_tools_ip_address\(\) \{' "system tools should define native ip detection helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^sshkey_on\(\) \{' "system tools should define native ssh key mode helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^add_sshkey\(\) \{' "system tools should define native ssh key generation helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^import_sshkey\(\) \{' "system tools should define native ssh key import helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^fetch_remote_ssh_keys\(\) \{' "system tools should define native remote ssh key fetch helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^fetch_github_ssh_keys\(\) \{' "system tools should define native github ssh key fetch helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^create_user_with_sshkey\(\) \{' "system tools should define native user creation with ssh key helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^fix_dpkg\(\) \{' "system tools should define native dpkg recovery helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^luopo_system_tools_write_dns\(\) \{' "system tools should define native dns writer helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^auto_optimize_dns\(\) \{' "system tools should define native dns optimization helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^linux_update\(\) \{' "system tools should define native update helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^linux_clean\(\) \{' "system tools should define native clean helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^f2b_status\(\) \{' "system tools should define native fail2ban status helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^f2b_install_sshd\(\) \{' "system tools should define native fail2ban install helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^luopo_system_tools_fail2ban_status_label\(\) \{' "system tools should define native fail2ban status label helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^k_info\(\) \{' "system tools should define native z command help"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^luopo_system_tools_render_cell\(\) \{' "missing LuoPo system tools render helper"
  assert_contains_regex "$LUOPO_SYSTEM_TOOLS_HELPERS_FILE" '^luopo_system_tools_print_user_table\(\) \{' "missing LuoPo system tools user table helper"

  assert_contains_fixed "$ROOT_DIR/core/menu.sh" 'source "$ROOT_DIR/core/runtime.sh"' "core menu should source shared runtime helpers"
  assert_contains_regex "$ROOT_DIR/core/runtime.sh" '^install\(\) \{' "shared runtime should define install helper"
  assert_contains_regex "$ROOT_DIR/core/runtime.sh" '^remove\(\) \{' "shared runtime should define remove helper"
  assert_contains_regex "$ROOT_DIR/core/runtime.sh" '^send_stats\(\) \{' "shared runtime should define stats helper"
  assert_contains_regex "$ROOT_DIR/core/runtime.sh" '^break_end\(\) \{' "shared runtime should define break helper"
  assert_contains_regex "$ROOT_DIR/core/runtime.sh" '^install_docker\(\) \{' "shared runtime should define docker installer helper"
  assert_contains_regex "$ROOT_DIR/core/runtime.sh" '^tmux_run\(\) \{' "shared runtime should define tmux attach helper"
  assert_contains_regex "$ROOT_DIR/core/runtime.sh" '^tmux_run_d\(\) \{' "shared runtime should define tmux background helper"
  assert_contains_regex "$ROOT_DIR/core/runtime.sh" '^bbr_on\(\) \{' "shared runtime should define bbr helper"
  assert_contains_regex "$ROOT_DIR/core/runtime.sh" '^server_reboot\(\) \{' "shared runtime should define reboot helper"
  assert_contains_regex "$ROOT_DIR/core/runtime.sh" '^add_sshpasswd\(\) \{' "shared runtime should define ssh password helper"
  assert_contains_fixed "$LUOPO_WARP_ACTIONS_FILE" 'bash menu.sh [option] [lisence/url/token]' "warp native command mismatch"
  assert_not_contains_fixed "$INSTALL_FILE" 'K_COMPAT_PATH="/usr/local/bin/k"' "install should not define k compatibility launcher"
  assert_contains_fixed "$INSTALL_FILE" 'rm -f /usr/local/bin/k /usr/bin/k' "install should cleanup legacy k launchers"
  assert_contains_fixed "$INSTALL_FILE" 'REPO_ARCHIVE_URL="${LUOPO_REPO_ARCHIVE_URL:-https://codeload.github.com/LuoPoJunZi/toolkit/tar.gz/refs/heads/main}"' "install should support remote bootstrap archive"
  assert_contains_fixed "$INSTALL_FILE" 'bootstrap_source_tree() {' "install bootstrap function missing"
  assert_contains_fixed "$INSTALL_FILE" 'SOURCE_DIR="$extracted_dir"' "install should switch to downloaded source tree"
  assert_contains_fixed "$INSTALL_FILE" '--exclude="vendor/luopo.sh"' "install should not copy local-only vendor snapshot"
  assert_contains_fixed "$UNINSTALL_FILE" 'rm -f /usr/local/bin/k /usr/bin/k' "uninstall should cleanup legacy k launchers"
  if git ls-files --error-unmatch vendor/luopo.sh >/dev/null 2>&1; then
    fail "vendor/luopo.sh should remain local-only and must not be tracked"
  fi

  echo "[PASS] menu routing smoke checks passed"
}

main "$@"
